### ISSUE TITLE
Fix the bug in the processor api handler

### ISSUE THREAD

**Issue by peymanmortazavi** [QuantifiedSelfless/gulper#14] opened 2016-04-09 04:50 UTC
in lib/processors/lib/util.py in the make_handler function on line 14.

we need to pass name

**Comment by mynameisfiber** [comment] 2016-04-09 17:22
QuantifiedSelfless/quantifiedSelf@e0664d8

**Comment by wannabeCitizen** [comment] 2016-04-09 17:27
I'm confused... Why is this being assigned to me and pointing to quantifiedSelf. Can we get more information on what this is about. 

I think Peyman was reporting a bug that the handler's don't create user objects (at least that's what he was telling me last night. Yet we have a user object implicit in all our handlers.

**Comment by wannabeCitizen** [comment] 2016-04-09 17:27
Assigning back to Micha until I can get more info since I don't even know what is being referenced here.

**Comment by mynameisfiber** [comment] 2016-04-09 17:28
i'm assuming the bug has something to do with code you pushed to master on quantifiedSelf which is why i'm assigning it to you.

**Comment by wannabeCitizen** [comment] 2016-04-09 17:30
I don't see how these are related? This is for the creation of the handlers for the processors. I can just add the user_name in there as well. Is that all that is being asked for? If so, I can assign back to myself for adding 1 line...

**Comment by mynameisfiber** [comment] 2016-04-09 17:31
me neither, the issue is one sentence that doesn't make too much sense to me... we've probably written 50x more text in the comments than the fix would probably have taken.

**Comment by wannabeCitizen** [comment] 2016-04-09 17:38
I already added support for the db connections in PR #12, I've now added a line that should take care of this bug: https://github.com/QuantifiedSelfless/gulper/pull/12/commits/69aa3335ca9dd790621985b6678f76d5623f0806#diff-a1bbb6d8cfe1424a029df819f8405f88R16

**Comment by mynameisfiber** [comment] 2016-04-19 05:51
i'm going to consider this one closed since i'm still not sure what it's about and it's been 10 days.

**Closed as completed by mynameisfiber** 2016-04-19 05:51 UTC
Labels: bug
